# Generated by Django 5.1.7 on 2025-04-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('symptom_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=100)),
            ],
        ),
    ]
